name: multi_state_button
description: A package which provides multiple states for a button with endless customizability.
version: 1.1.3
#author: Bharath
homepage: https://github.com/Bharathh-Raj/multi_state_button

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: